name: Code Scanning

on:
  push:
  pull_request:
    branches: [ master ]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:

  code-ql:
    strategy:
      matrix:
        language: [ 'cpp' ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install --yes --quiet --no-install-recommends \
          libasound2-dev \
          libbluetooth-dev \
          libbsd-dev \
          libdbus-1-dev \
          libfdk-aac-dev \
          libglib2.0-dev \
          libmp3lame-dev \
          libmpg123-dev \
          libncurses5-dev \
          libreadline-dev \
          libsbc-dev \
          libspandsp-dev
    - uses: actions/checkout@v3
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        queries: security-and-quality
    - name: Create Build Environment
      run: |
        mkdir -p ${{ github.workspace }}/{build,m4}
        autoreconf --install
    - name: Configure GNU Automake
      working-directory: ${{ github.workspace }}/build
      run: |
        ${{ github.workspace }}/configure \
          --enable-aac \
          --enable-faststream \
          --enable-mp3lame \
          --enable-mpg123 \
          --enable-msbc \
          --enable-ofono \
          --enable-upower \
          --enable-aplay \
          --enable-cli \
          --enable-rfcomm \
          --enable-a2dpconf \
          --enable-hcitop
    - name: Build
      working-directory: ${{ github.workspace }}/build
      run: make
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

  doc8-lint:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run reStructuredText Linter
      uses: deep-entertainment/doc8-action@v4
      with:
        ignorePaths: ${{ github.workspace }}/doc/bluealsa-api.txt
        scanPaths: ${{ github.workspace }}

  markdown-lint:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Markdown Linter
      uses: nosborn/github-action-markdown-cli@v3
      with:
        files: ${{ github.workspace }}

  shellcheck:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run ShellCheck Scan
      uses: arkq/action-shellcheck@master
      with:
        additional_files: misc/bash-completion/bluealsa
        format: sarif
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results
